# Generated by Django 5.2.6 on 2026-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_tickets_cliente_f1989d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=True, verbose_name='Precisa trocar senha no próximo login'),
        ),
    ]
