# Generated by Django 5.2.6 on 2026-02-04 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_cliente_precisa_trocar_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='cliente',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='clientes',
            field=models.ManyToManyField(related_name='ambientes', to=settings.AUTH_USER_MODEL, verbose_name='Clientes com acesso'),
        ),
    ]
