# Generated by Django 5.2.6 on 2026-02-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0020_remove_ambiente_cliente_ambiente_clientes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="owner",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Proprietário (Maximo ID)",
            ),
        ),
    ]
