# Generated by Django 5.2.6 on 2026-02-10 13:18

import django.db.models.deletion
import tickets.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0021_ticket_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="anexo",
        ),
        migrations.CreateModel(
            name="TicketAnexo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to=tickets.models.ticket_upload_path),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="tickets.ticket",
                    ),
                ),
            ],
        ),
    ]
