# Generated by Django 5.2.6 on 2026-02-19 17:12

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0022_remove_ticket_anexo_ticketanexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="documento_requisicao",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=tickets.models.ticket_upload_path,
                verbose_name="Documento de Requisição",
            ),
        ),
    ]
