# Generated by Django 5.2.6 on 2026-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0023_ticket_documento_requisicao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status_maximo",
            field=models.CharField(
                choices=[
                    ("NEW", "Novo"),
                    ("QUEUED", "Em fila"),
                    ("INPROG", "Em Andamento"),
                    ("PENDING", "Pendente"),
                    ("APPR", "Aprovado"),
                    ("APPFML", "Aprovado pelo Gerenciador de Cumprimento"),
                    ("APPLM", "Aprovado pelo Gerente de Linha"),
                    ("RESOLVED", "Resolvido"),
                    ("CLOSED", "Fechado"),
                    ("CANCELLED", "Cancelado"),
                    ("REJECTED", "Rejeitado"),
                    ("DRAFT", "Rascunho"),
                    ("HISTEDIT", "Editado no Histórico"),
                    ("TSTCLI", "Teste do cliente"),
                    ("TSTCLIOK", "Teste do cliente OK"),
                    ("TSTCLIFAIL", "Teste do cliente falhou"),
                    ("IMPPRODOK", "Implementação em produção OK"),
                    ("AGREUN", "Reunião Agendada"),
                    ("CRITFAIL", "Falha Crítica"),
                    ("ROLLBACK", "Rollback"),
                    ("TREINAMTO", "Treinamento"),
                    ("DOC", "Documentar"),
                ],
                default="NEW",
                max_length=20,
                verbose_name="Status Atual",
            ),
        ),
    ]
