# Generated by Django 5.2.6 on 2026-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0024_alter_ticket_status_maximo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status_maximo",
            field=models.CharField(
                choices=[
                    ("NEW", "Novo"),
                    ("QUEUED", "Em fila"),
                    ("INPROG", "Em Andamento"),
                    ("PENDING", "Pendente"),
                    ("RESOLVED", "Resolvido"),
                    ("CLOSED", "Fechado"),
                    ("CANCELLED", "Cancelado"),
                    ("REJECTED", "Rejeitado"),
                    ("TSTCLI", "Teste do cliente"),
                    ("TSTCLIOK", "Teste do cliente OK"),
                    ("TSTCLIFAIL", "Teste do cliente falhou"),
                    ("IMPPRODOK", "Implementação em produção OK"),
                    ("AGREUN", "Reunião Agendada"),
                    ("TREINAMTO", "Treinamento"),
                    ("DOC", "Documentar"),
                ],
                default="NEW",
                max_length=20,
                verbose_name="Status Atual",
            ),
        ),
    ]
