# Generated by Django 5.2.6 on 2026-05-22 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0025_alter_ticket_status_maximo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_equipamento", models.CharField(max_length=100)),
                ("numero_ativo", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
                "db_table": "equipamentos",
                "ordering": ["nome_equipamento"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="equipamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="tickets.equipamento",
                verbose_name="Equipamento Afetado",
            ),
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_local", models.CharField(max_length=100)),
                ("numero_ativo", models.CharField(max_length=20)),
                (
                    "clientes",
                    models.ManyToManyField(
                        related_name="locais",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Clientes com acesso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local",
                "verbose_name_plural": "Locais",
                "db_table": "locais",
                "ordering": ["nome_local"],
            },
        ),
        migrations.AddField(
            model_name="equipamento",
            name="local",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipamentos",
                to="tickets.local",
                verbose_name="Local",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="tickets.local",
                verbose_name="Local Afetado",
            ),
        ),
        migrations.AddIndex(
            model_name="equipamento",
            index=models.Index(fields=["local"], name="equipamento_local_i_e4d654_idx"),
        ),
    ]
