# Generated by Django 5.2.6 on 2026-05-22

from django.db import migrations


def criar_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="IoT_Cliente")
    Group.objects.get_or_create(name="IoT_Suporte")


def remover_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["IoT_Cliente", "IoT_Suporte"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0026_equipamento_ticket_equipamento_local_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(criar_grupos, remover_grupos),
    ]
