# Generated by Django 5.2.6 on 2026-05-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0027_iot_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="local",
            name="numero_ativo",
        ),
    ]
