# Generated by Django 5.2.6 on 2026-06-22 18:57

import django.db.models.deletion
import tickets.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0028_remove_area_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteracaoAnexo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=tickets.models.interacao_anexo_upload_path
                    ),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "interacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="tickets.ticketinteracao",
                    ),
                ),
            ],
            options={
                "ordering": ["data_envio"],
            },
        ),
    ]
