# Generated by Django 5.2.6 on 2026-06-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0029_interacaoanexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="anexos_sincronizados",
            field=models.BooleanField(
                default=True, verbose_name="Anexos sincronizados com o Maximo"
            ),
        ),
    ]
