# Generated by Django 5.2.6 on 2026-06-29 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0030_ticket_anexos_sincronizados"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="seguidores",
            field=models.ManyToManyField(
                blank=True,
                related_name="tickets_seguindo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Seguidores (acompanham o ticket)",
            ),
        ),
    ]
