# Generated by Django 5.2.6 on 2026-07-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0031_ticket_seguidores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("mensagem", "Nova Mensagem"),
                    ("status", "Mudança de Status"),
                    ("sistema", "Aviso do Sistema"),
                    ("novo_ticket", "Novo Ticket"),
                ],
                default="sistema",
                max_length=20,
            ),
        ),
    ]
