# Generated by Django 5.2.6 on 2026-07-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0032_alter_notificacao_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketinteracao",
            name="editado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Editado em"
            ),
        ),
    ]
