# Generated by Django 5.2.6 on 2026-07-08 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0033_ticketinteracao_editado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="colegas_notificados",
            field=models.ManyToManyField(
                blank=True,
                related_name="tickets_acompanhando_como_colega",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Colegas notificados (escolhidos pelo solicitante)",
            ),
        ),
    ]
