# Generated by Django 5.2.6 on 2026-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0034_ticket_colegas_notificados"),
    ]

    operations = [
        migrations.AddField(
            model_name="interacaoanexo",
            name="maximo_doclink_id",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="ID do doclink no Maximo",
            ),
        ),
    ]
