# Generated by Django 5.2.6 on 2026-07-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0036_backfill_colegas_interagentes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailPendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinatario", models.EmailField(max_length=254)),
                ("assunto", models.CharField(max_length=255)),
                ("corpo_html", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("tentativas", models.PositiveIntegerField(default=0)),
                ("ultimo_erro", models.TextField(blank=True)),
                ("ultima_tentativa_em", models.DateTimeField(blank=True, null=True)),
                ("desistiu", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["criado_em"],
            },
        ),
    ]
