# Generated by Django 5.2.6 on 2026-08-13 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0037_emailpendente"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModoManutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=False)),
                (
                    "mensagem",
                    models.CharField(
                        default="O portal está em manutenção. A abertura de novos tickets está temporariamente indisponível.",
                        max_length=255,
                    ),
                ),
                (
                    "previsao_retorno",
                    models.DateTimeField(
                        blank=True,
                        help_text="Opcional. Exibida no aviso quando preenchida.",
                        null=True,
                    ),
                ),
                ("ativado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "ativado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutencoes_ativadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Modo de manutenção",
                "verbose_name_plural": "Modo de manutenção",
            },
        ),
    ]
